CREATE TABLE `TURNIRI_REZULTATI` (
  `ID_REZULTAT` int(11) NOT NULL,
  `UUID_BORD` varchar(36) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `UUID_TURNIR` varchar(36) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `NS_PAIR` int(11) NOT NULL,
  `EW_PAIR` int(11) NOT NULL,
  `CONTRACT` varchar(10) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `RBR_BOARD` int(11) NOT NULL,
  `DECLARER` varchar(1) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `LEAD` varchar(4) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `DECLARER_TRICKS` int(11) NOT NULL,
  `NS_REZULTAT` int(11) NOT NULL,
  `ISBYE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_REZULTAT`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

