CREATE TABLE `TURNIRI_BORDOVI` (
  `ID_BORD` int(11) NOT NULL,
  `ID_TURNIR` int(11) NOT NULL,
  `RBR_BORD` int(11) NOT NULL,
  `UUID_TURNIR` varchar(36) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `UUID_BORD` varchar(36) CHARACTER SET utf8 COLLATE utf8_croatian_ci NOT NULL,
  `DLM` varchar(26) CHARACTER SET ascii NOT NULL,
  `VRIJEME` datetime NOT NULL,
  PRIMARY KEY (`ID_BORD`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

